import { useCallback } from "react";
import { useNavigate } from "react-router-dom";
import TableHeader from "./TableHeader";
import TableCell from "./TableCell";
import ButtonStyle from "./ButtonStyle";
import PropTypes from "prop-types";
import styles from "./GradesTable.module.css";

const GradesTable = ({ className = "", size = "Default" }) => {
  const navigate = useNavigate();

  const onButtonStyle1ContainerClick = useCallback(() => {
    navigate("/desktopmodal");
  }, [navigate]);

  return (
    <div className={[styles.gradesTable, className].join(" ")} data-size={size}>
      <TableHeader
        property1="Default"
        tableHeader="Primer Parcial"
        showTableHeader
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="11.74%"
        tableHeaderTop="0%"
        tableHeaderRight="37.32%"
        tableHeaderBottom="83.33%"
        tableHeaderLeft="50.94%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Segundo Parcial"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="11.74%"
        tableHeaderTop="0%"
        tableHeaderRight="25.58%"
        tableHeaderBottom="83.33%"
        tableHeaderLeft="62.67%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Tercer Parcial"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="11.74%"
        tableHeaderTop="0%"
        tableHeaderRight="13.84%"
        tableHeaderBottom="83.33%"
        tableHeaderLeft="74.42%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Cuarto Parcial"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="4.49%"
        tableHeaderTop="16.67%"
        tableHeaderRight="56.32%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="39.19%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Faltas"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="4.49%"
        tableHeaderTop="16.67%"
        tableHeaderRight="44.57%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="50.94%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Faltas"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="4.49%"
        tableHeaderTop="16.67%"
        tableHeaderRight="32.84%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="62.67%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Faltas"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="4.49%"
        tableHeaderTop="16.67%"
        tableHeaderRight="21.09%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="74.42%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Faltas"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="7.26%"
        tableHeaderTop="16.67%"
        tableHeaderRight="49.06%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="43.68%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Calificación"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="7.26%"
        tableHeaderTop="16.67%"
        tableHeaderRight="37.32%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="55.43%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Calificación"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="7.26%"
        tableHeaderTop="16.67%"
        tableHeaderRight="25.58%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="67.16%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Calificación"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="16.67%"
        tableHeaderWidth="7.26%"
        tableHeaderTop="16.67%"
        tableHeaderRight="13.84%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="78.91%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Calificación"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="33.33%"
        tableHeaderWidth="6.35%"
        tableHeaderTop="0%"
        tableHeaderRight="7.48%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="86.16%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Ordinario"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="33.33%"
        tableHeaderWidth="7.48%"
        tableHeaderTop="0%"
        tableHeaderRight="0%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="92.52%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        showTableHeader={false}
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableCell size="Default" tableCell="123456" showTableCell />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="8.6%"
        tableCellTop="50%"
        tableCellRight="91.4%"
        tableCellBottom="33.33%"
        tableCellLeft="0%"
        tableCellMargin="unset"
        tableCell="123456"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="8.6%"
        tableCellTop="66.67%"
        tableCellRight="91.4%"
        tableCellBottom="16.67%"
        tableCellLeft="0%"
        tableCellMargin="unset"
        tableCell="123456"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="8.6%"
        tableCellTop="83.33%"
        tableCellRight="91.4%"
        tableCellBottom="0%"
        tableCellLeft="0%"
        tableCellMargin="unset"
        tableCell="123456"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="33.33%"
        tableCellRight="56.32%"
        tableCellBottom="50%"
        tableCellLeft="39.19%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="50%"
        tableCellRight="56.32%"
        tableCellBottom="33.33%"
        tableCellLeft="39.19%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="66.67%"
        tableCellRight="56.32%"
        tableCellBottom="16.67%"
        tableCellLeft="39.19%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="83.33%"
        tableCellRight="56.32%"
        tableCellBottom="0%"
        tableCellLeft="39.19%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="33.33%"
        tableCellRight="44.57%"
        tableCellBottom="50%"
        tableCellLeft="50.94%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="50%"
        tableCellRight="44.57%"
        tableCellBottom="33.33%"
        tableCellLeft="50.94%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="66.67%"
        tableCellRight="44.57%"
        tableCellBottom="16.67%"
        tableCellLeft="50.94%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="83.33%"
        tableCellRight="44.57%"
        tableCellBottom="0%"
        tableCellLeft="50.94%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="33.33%"
        tableCellRight="32.84%"
        tableCellBottom="50%"
        tableCellLeft="62.67%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="50%"
        tableCellRight="32.84%"
        tableCellBottom="33.33%"
        tableCellLeft="62.67%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="66.67%"
        tableCellRight="32.84%"
        tableCellBottom="16.67%"
        tableCellLeft="62.67%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="83.33%"
        tableCellRight="32.84%"
        tableCellBottom="0%"
        tableCellLeft="62.67%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="33.33%"
        tableCellRight="21.09%"
        tableCellBottom="50%"
        tableCellLeft="74.42%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="50%"
        tableCellRight="21.09%"
        tableCellBottom="33.33%"
        tableCellLeft="74.42%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="66.67%"
        tableCellRight="21.09%"
        tableCellBottom="16.67%"
        tableCellLeft="74.42%"
        tableCellMargin="unset"
        tableCell="0"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="4.49%"
        tableCellTop="83.33%"
        tableCellRight="21.09%"
        tableCellBottom="0%"
        tableCellLeft="74.42%"
        tableCellMargin="unset"
        tableCell="-"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="33.33%"
        tableCellRight="49.06%"
        tableCellBottom="50%"
        tableCellLeft="43.68%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="50%"
        tableCellRight="49.06%"
        tableCellBottom="33.33%"
        tableCellLeft="43.68%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="66.67%"
        tableCellRight="49.06%"
        tableCellBottom="16.67%"
        tableCellLeft="43.68%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="83.33%"
        tableCellRight="49.06%"
        tableCellBottom="0%"
        tableCellLeft="43.68%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="33.33%"
        tableCellRight="37.32%"
        tableCellBottom="50%"
        tableCellLeft="55.43%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="50%"
        tableCellRight="37.32%"
        tableCellBottom="33.33%"
        tableCellLeft="55.43%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="66.67%"
        tableCellRight="37.32%"
        tableCellBottom="16.67%"
        tableCellLeft="55.43%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="83.33%"
        tableCellRight="37.32%"
        tableCellBottom="0%"
        tableCellLeft="55.43%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="33.33%"
        tableCellRight="25.58%"
        tableCellBottom="50%"
        tableCellLeft="67.16%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="50%"
        tableCellRight="25.58%"
        tableCellBottom="33.33%"
        tableCellLeft="67.16%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="66.67%"
        tableCellRight="25.58%"
        tableCellBottom="16.67%"
        tableCellLeft="67.16%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="83.33%"
        tableCellRight="25.58%"
        tableCellBottom="0%"
        tableCellLeft="67.16%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="33.33%"
        tableCellRight="13.84%"
        tableCellBottom="50%"
        tableCellLeft="78.91%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="6.35%"
        tableCellTop="33.33%"
        tableCellRight="7.48%"
        tableCellBottom="50%"
        tableCellLeft="86.16%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.48%"
        tableCellTop="33.33%"
        tableCellRight="0%"
        tableCellBottom="50%"
        tableCellLeft="92.52%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell={false}
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="50%"
        tableCellRight="13.84%"
        tableCellBottom="33.33%"
        tableCellLeft="78.91%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="6.35%"
        tableCellTop="50%"
        tableCellRight="7.48%"
        tableCellBottom="33.33%"
        tableCellLeft="86.16%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.48%"
        tableCellTop="50%"
        tableCellRight="0%"
        tableCellBottom="33.33%"
        tableCellLeft="92.52%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell={false}
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="66.67%"
        tableCellRight="13.84%"
        tableCellBottom="16.67%"
        tableCellLeft="78.91%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="6.35%"
        tableCellTop="66.67%"
        tableCellRight="7.48%"
        tableCellBottom="16.67%"
        tableCellLeft="86.16%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.48%"
        tableCellTop="66.67%"
        tableCellRight="0%"
        tableCellBottom="16.67%"
        tableCellLeft="92.52%"
        tableCellMargin="unset"
        tableCell="8.5"
        showTableCell={false}
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.26%"
        tableCellTop="83.33%"
        tableCellRight="13.84%"
        tableCellBottom="0%"
        tableCellLeft="78.91%"
        tableCellMargin="unset"
        tableCell="-"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="6.35%"
        tableCellTop="83.33%"
        tableCellRight="7.48%"
        tableCellBottom="0%"
        tableCellLeft="86.16%"
        tableCellMargin="unset"
        tableCell="-"
        showTableCell
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="16.67%"
        tableCellWidth="7.48%"
        tableCellTop="83.33%"
        tableCellRight="0%"
        tableCellBottom="0%"
        tableCellLeft="92.52%"
        tableCellMargin="unset"
        tableCell="-"
        showTableCell={false}
        tableCellTextAlign="left"
        tableCellFlex="unset"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="17.67%"
        tableCellWidth="30.59%"
        tableCellTop="32.85%"
        tableCellRight="60.81%"
        tableCellBottom="49.48%"
        tableCellLeft="8.6%"
        tableCellMargin="unset"
        tableCell="Nombre Apellido"
        showTableCell
        tableCellTextAlign="center"
        tableCellFlex="1"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="17.67%"
        tableCellWidth="30.59%"
        tableCellTop="49.52%"
        tableCellRight="60.81%"
        tableCellBottom="32.81%"
        tableCellLeft="8.6%"
        tableCellMargin="unset"
        tableCell="Nombre Apellido"
        showTableCell
        tableCellTextAlign="center"
        tableCellFlex="1"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="17.67%"
        tableCellWidth="30.59%"
        tableCellTop="66.18%"
        tableCellRight="60.81%"
        tableCellBottom="16.14%"
        tableCellLeft="8.6%"
        tableCellMargin="unset"
        tableCell="Nombre Apellido"
        showTableCell
        tableCellTextAlign="center"
        tableCellFlex="1"
      />
      <TableCell
        size="Default"
        tableCellPosition="absolute"
        tableCellHeight="17.67%"
        tableCellWidth="30.59%"
        tableCellTop="82.85%"
        tableCellRight="60.81%"
        tableCellBottom="-0.52%"
        tableCellLeft="8.6%"
        tableCellMargin="unset"
        tableCell="Nombre Apellido"
        showTableCell
        tableCellTextAlign="center"
        tableCellFlex="1"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="33.33%"
        tableHeaderWidth="8.6%"
        tableHeaderTop="0%"
        tableHeaderRight="91.4%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="0%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Clave"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <TableHeader
        property1="Default"
        tableHeaderPosition="absolute"
        tableHeaderHeight="33.33%"
        tableHeaderWidth="30.59%"
        tableHeaderTop="0%"
        tableHeaderRight="60.81%"
        tableHeaderBottom="66.67%"
        tableHeaderLeft="8.6%"
        tableHeaderAlignSelf="unset"
        tableHeaderFlex="unset"
        tableHeader="Nombre"
        showTableHeader
        tableHeaderFontSize="14px"
        tableHeaderFontFamily="'Open Sans'"
      />
      <ButtonStyle
        state="Default"
        buttonStyle1Width="4.86%"
        buttonStyle1Height="7.19%"
        onButtonStyle1ContainerClick={onButtonStyle1ContainerClick}
        buttonStyle1Position="absolute"
        buttonStyle1Top="37.87%"
        buttonStyle1Right="1.35%"
        buttonStyle1Bottom="54.94%"
        buttonStyle1Left="93.79%"
        button="Actualizar"
        button1="Actualizar"
      />
      <ButtonStyle
        state="Default"
        buttonStyle1Width="4.86%"
        buttonStyle1Height="7.19%"
        onButtonStyle1ContainerClick={onButtonStyle1ContainerClick}
        buttonStyle1Position="absolute"
        buttonStyle1Top="54.54%"
        buttonStyle1Right="1.35%"
        buttonStyle1Bottom="38.27%"
        buttonStyle1Left="93.79%"
        button="Actualizar"
        button1="Actualizar"
      />
      <ButtonStyle
        state="Default"
        buttonStyle1Width="4.86%"
        buttonStyle1Height="7.19%"
        onButtonStyle1ContainerClick={onButtonStyle1ContainerClick}
        buttonStyle1Position="absolute"
        buttonStyle1Top="71.2%"
        buttonStyle1Right="1.35%"
        buttonStyle1Bottom="21.61%"
        buttonStyle1Left="93.79%"
        button="Actualizar"
        button1="Actualizar"
      />
      <ButtonStyle
        state="Default"
        buttonStyle1Width="4.86%"
        buttonStyle1Height="7.19%"
        onButtonStyle1ContainerClick={onButtonStyle1ContainerClick}
        buttonStyle1Position="absolute"
        buttonStyle1Top="88.27%"
        buttonStyle1Right="1.35%"
        buttonStyle1Bottom="4.54%"
        buttonStyle1Left="93.79%"
        button="Actualizar"
        button1="Actualizar"
      />
    </div>
  );
};

GradesTable.propTypes = {
  className: PropTypes.string,

  /** Variant props */
  size: PropTypes.number,
};

export default GradesTable;
